apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-ss-configuration
  namespace: redis-latest
  labels:
    app: redis
data:
  master.conf: |
    maxmemory 50mb
    maxmemory-policy allkeys-lru
    maxclients 20000
    timeout 300
    appendonly no
    dbfilename dump.rdb
    dir /data
  slave.conf: |
    slaveof redis-ss-0.redis-ss.redis 6379
    maxmemory 50mb
    maxmemory-policy allkeys-lru
    maxclients 20000
    timeout 300
    dir /data